version: 2
jobs:
  build:
    docker:
      - image: cypress/base:12.14.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: cd example && yarn install
      - run: npm install -g wait-on

      - save_cache:
          paths:
            - node_modules
            - example/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: cd example && echo "SKIP_PREFLIGHT_CHECK=true" > .env
      - run: cd example && bin/cypress
